maxForce: 30
motionDriftNoise: 0.0
motionDriftNoiseTime: 50
motionSmallNoise: 0.0
namespace: /simple_drone
positionXYDifferentialGain: 0.0
positionXYIntegralGain: 0.0
positionXYLimit: 20
positionXYProportionalGain: 1.1
positionZDifferentialGain: 0.2
positionZIntegralGain: 0.0
positionZLimit: -1
positionZProportionalGain: 1.0
rollpitchDifferentialGain: 5.0
rollpitchLimit: 0.5
rollpitchProportionalGain: 6.0
velocityXYDifferentialGain: 2.3
velocityXYLimit: 2
velocityXYProportionalGain: 5.0
velocityZDifferentialGain: 1.0
velocityZIntegralGain: 0.0
velocityZLimit: -1
velocityZProportionalGain: 5.0
yawDifferentialGain: 1.0
yawLimit: 1.5
yawProportionalGain: 2.0
